### ISSUE TITLE
[BUG]: PR template link points to invalid address

### ISSUE THREAD

**Issue by ghost** [predictionmachine/pm-coding-template#24]
In the coding standards manual, the link attached to the PR template points to an invalid URL. I assume the reason for this is that the `.github` folder has been moved from `docs` to top level, but the link hasn't been updated accordingly. This is just a minor issue, yet it would be nice to fix it.

**Steps to Reproduce:**
1. Go to `docs/coding-standard.md`.
2. Click on the link in the 6th bulletpoint under the subtitle **Github: branches, pull requests** (*Use **this** PR template...*)
3. See 404 error.

**Comment by tchklovski** [comment]
Nice catch! we should probably run a broken-link-checker someday. A recent change is that the PR template now is available organization-wide, and comes from [here](https://github.com/predictionmachine/.github/blob/main/.github/pull_request_template.md) in the `.github` repo (see predictionmachine/.github#4).

@hanga-predmachine, I think in this case we can just drop that bullet point, since the template is used automagically, and "best feature is no feature" -- ie if we don't have the documentation we don't have to maintain its correctness

**Comment by abhishekmishragithub** [comment]
@hanga-predmachine there is another broken URL in the doc. 
You can find it under [Code Contents](https://github.com/predictionmachine/pm-coding-template/blob/main/docs/coding-standard.md#code-contents) header inside License & Type hint sections.

The reference to [projectname/example.py](https://github.com/predictionmachine/pm-coding-template/blob/main/projectname/example.py) is relative path and it's throwing 404.

The line with broken URL is: 
> See projectname/example.py for an example

If you are planning to do PR for initial issue then please add fix for above broken links as well.

**Comment by abhishekmishragithub** [comment]
Fixed in #27 
Closing the issue 🐥
